In [52]:
import pandas as pd

In [53]:
df1=pd.read_csv("03_Library Systembook.csv")
df2=pd.read_csv("03_Library SystemCustomers.csv")

In [54]:
issues_in_df1=[df1[df1["Books"].isna() | df1["Customer ID"].isna()]]

print("Rows with missing values in Dataset 1")
print(issues_in_df1)

issues_in_df2=df2[df2["Customer ID"].isna()]

print("Rows with missing values in Dataset 2")
print(issues_in_df2)

Rows with missing values in Dataset 1
[       Id Books Book checkout Book Returned Days allowed to borrow  \
20   21.0   NaN  "01/06/2023"    05/06/2023                2 weeks
21    NaN   NaN           NaN           NaN                    NaN
22    NaN   NaN           NaN           NaN                    NaN
23    NaN   NaN           NaN           NaN                    NaN
24    NaN   NaN           NaN           NaN                    NaN
..    ...   ...           ...           ...                    ...
109   NaN   NaN           NaN           NaN                    NaN
110   NaN   NaN           NaN           NaN                    NaN
111   NaN   NaN           NaN           NaN                    NaN
112   NaN   NaN           NaN           NaN                    NaN
113   NaN   NaN           NaN           NaN                    NaN

     Customer ID
20           NaN
21           NaN
22           NaN
23           NaN
24           NaN
..           ...
109          NaN
110          NaN
111          NaN
112          NaN
113          NaN

[94 rows x 6 columns]]
Rows with missing values in Dataset 2
   Customer ID Customer Name
3          NaN           NaN

In [55]:
df1["Book Returned"]=pd.to_datetime(df1["Book Returned"], format="%d/%m/%Y")
df1["Book checkout"]=df1["Book checkout"].astype(str).str.replace("2063","2023")
df1["Book checkout"]=pd.to_datetime(df1["Book checkout"].astype(str).str.replace('"','', regex=False), format="%d/%m/%Y", errors="coerce")

df1.dropna(inplace=True)
df1.reset_index(drop=True, inplace=True)

df2.dropna(how="all", inplace=True)
df2.reset_index(drop=True, inplace=True)

df2['Customer ID']=range(1,len(df2)+1)
df2.head(7)

   Customer ID     Customer Name
0            1          Jane Doe
1            2        John Smith
2            3        Dan Reeves
3            4    William Holden
4            5     Jaztyn Forest
5            6     Jackie Irving
6            7  Matthew Stirling

In [56]:
df1.to_csv("clean_data.csv", index=False)
df1.head(21)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1.0,Catcher in the Rye,2023-02-20,2023-02-25,2 weeks,1.0
1,2.0,Lord of the rings the two towers,2023-03-24,2023-03-21,2 weeks,2.0
2,3.0,Lord of the rings the return of the kind,2023-03-29,2023-03-25,2 weeks,3.0
3,4.0,The hobbit,2023-04-02,2023-03-25,2 weeks,4.0
4,5.0,Dune,2023-04-02,2023-03-25,2 weeks,5.0
5,6.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0
6,7.0,IT,2023-04-10,2023-04-03,2 weeks,6.0
7,8.0,Misery,2023-04-15,2023-04-03,2 weeks,7.0
8,9.0,Catch 22,2023-04-15,2023-04-16,2 weeks,7.0
9,10.0,Animal Farm,2023-04-20,2023-04-24,2 weeks,2.0
10,11.0,1984,2023-04-23,2023-04-27,2 weeks,8.0
11,12.0,Little Women,2023-04-02,2023-05-01,2 weeks,1.0
12,13.0,East of Eden,2023-04-30,2023-05-05,2 weeks,2.0
13,14.0,America Is in the Heart,2023-05-01,2023-05-07,2 weeks,3.0
14,15.0,Wuthering Heights,2023-05-01,2023-05-10,2 weeks,9.0
15,16.0,Dark Tales,2023-05-15,2023-06-01,2 weeks,2.0
16,18.0,Les Miserables,2023-06-03,2023-06-07,2 weeks,5.0
17,19.0,Dracula,2023-06-10,2023-07-10,2 weeks,10.0
18,20.0,Frankenstein,2023-06-01,2023-06-20,2 weeks,2.0

In [57]:
df2.to_csv("clean_data2.csv", index=False)
print(df1['Book checkout'].isna().sum())

0